---
- hosts: CentOS
  vars:
    http_port: 80
    max_clients: 200
  become: true
  become_user: root
  tasks:
  - name: ensure apache is at the latest version
    yum: pkg=httpd state=latest update_cache=yes
 
  - name: replace default index.html file
    copy: src=/static_files/index.html dest=/var/www/html/ mode=644
    notify:
    - restart apache
 
  - name: ensure apache is running (and enable it at boot)
    service: name=httpd state=started enabled=yes
  handlers:
    - name: restart apache
      service: name=httpd state=restarted
