---

#Setup security group
#Spin up instances
#Wait for SSH to be active

- hosts: localhost
  tasks:
    - name: Setting up security forewall group
      ec2_group:
        name: Created_Ansible_automation_group
        description: Allowing traffic on port 22 & 80
        region: us-west-2
        rules:
         - proto: tcp
           from_port: 80
           to_port: 80
           cidr_ip: 0.0.0.0/0
         - proto: ssh
           from:port: 22
           to_port: 22
           cidr_ip: 0.0.0.0/0
        rules_egress:
         - proto: all
           cidr_ip: 0.0.0.0/0

    - name: Provision a ec2 instance
      ec2:
        key_name: ansible_key
        region: us-west-2
	instance_type: t2.micro
        image: ami-77et56v
        wait: yes
        wait_timeout: 500
	count: 1
	instance_tags:
          name: awslabserver
	  owner: vinay
	monitoring: no
	vpc_subnet_id: subnet-76576et8
	assign_public_ip: yes
	group: Created_Ansible_automation_group
      register: ec2_out

   - name: wait for SSH to come up
     wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
     with_items: '{{ec2_out.instances}}'
