---
- hosts: web1
  sudo: yes
  vars:
    http_port: 80
    max_clients: 5
    doc_dir: /ansible/
    doc_root: /var/www/html/ansible/

  vars_prompt:
    - name: username
      prompt: what is your name?

  tasks:
  - name: Ensure Apache is installed
    yum: name=httpd state=present
    when: ansible_os_family == "RedHat"

  - name: Ensure Apache is started
    service: name=httpd enabled=yes state=started

  - name: Deploy configuration file
    template: src=example_templates/httpd.j2 dest=/etc/httpd/conf/httpd.conf
    notify:
      - Restart Apache

  - name: copy index file
    template: src=example_templates/index.j2 dest={{ doc_root }}/index.html

  handlers:
  - name: Restart Apache
    service: name=httpd state=restarted


- hosts: db1
  sudo: yes
  tasks:
  - name: Ensure MySQL is installed
    yum: name=mysql-server state=latest
  - name: Ensure MySQL service is started
    service: name=mysqld state=started

- hosts: webservers:dbservers
  sudo: yes
  tasks:
  - name: Ensure IPTABLES are off
    service: name=iptables state=stopped

