---
- hosts: CentOS
  become: true
  become_user: root
  
  tasks:
    - name: Install the basic pkg to the system
      yum: name={{ item }} state=latest update_cache=yes
      with_items:
        - epel-release
        - python
       
